### ISSUE TITLE
Masquer le contenu du champ password

### ISSUE THREAD

**Issue by hbooo** [thcolin/sensorr#107]
Le champ password dans les settings de sensorr est en clair pour l'authentification.

Il serait mieux de le masquer pour éviter que tout le monde puisse voir le mot de passe en jetant un oeil sur l'écran lors de la configuration

**Comment by Magicalex** [comment]
il faut changer `type="text"` par `type="password"`
https://github.com/thcolin/sensorr/blob/master/src/views/pages/Settings/blocks/Authentication.js#L24

**Comment by thcolin** [comment]
Fixed, thanks !
