### ISSUE TITLE
Error message ENOTFOUND

### ISSUE THREAD

**Issue by jnofsinger** [thcolin/sensorr#127]
When using Jackett to search for movies I can get results and add a title to be downloaded.  Whenever I click on "Grab a manual ticket" or force a "record" action this always shows up in the log file as error.

From my understanding when it "records" it should send the magnet link to the blackhole directory.  Is this not the case?  What action sends a link to the locally configured directory?

"err": {
      "message": "request to http://magnet/?xt=urn:btih:659eae1f5dd3def74e571a44665fa22972aa706e&dn=Vanilla+Sky+%25282001%2529+720p+x264+-+750MB+-+YIFY&tr=udp%253A%252F%252Ftracker.leechers-paradise.org%253A6969&tr=udp%253A%252F%252Ftracker.openbittorrent.com%253A80&tr=udp%253A%252F%252Fopen.demonii.com%253A1337&tr=udp%253A%252F%252Ftracker.coppersurfer.tk%253A6969&tr=udp%253A%252F%252Fexodus.desync.com%253A6969 failed, reason: getaddrinfo ENOTFOUND magnet",
      "type": "system",
      "errno": "ENOTFOUND",
      "code": "ENOTFOUND"
    },
    "code": "ENOTFOUND"

**Comment by thcolin** [comment]
Hello,

Because `sensorr` only support `blackhole` strategy for downloading release (with `.torrent` or `.nzb` files), `magnet` download will not work, you should configure `Jackett` trackers to use `.torrent` file for download
