### ISSUE TITLE
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["WWW-Authenticate"]

### ISSUE THREAD

**Issue by l0ghan** [thcolin/sensorr#152]
Hello there :)
Thank you first for this amazing tool and the amont of work.
I've an issue with the latest version with this environment :
- synology
- docker

run command : 
docker run -p 5070:5070 -e TZ=Europe/Paris -v [config folder]:/app/sensorr/config -v [blackhole folder]:/app/sensorr/blackhole --name="sensorr" thcolin/sensorr:latest

config : 
défaut config.json and custom (v0.9) config.json with same results

`2020-05-13T00:18:50: PM2 error: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (28) | stderr
-- | --`
--> not blocking error

`TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["WWW-Authenticate"] | stderr
-- | --`
--> Internal Server Error

I can give more details about it if needed and I'll be glad to help
julien

**Comment by thcolin** [comment]
Hello,

Sorry, I tried to add an emoji to the basic auth realm and it failed miserably haha
Try the `latest` tag, I build a new version days ago which fix this bug
