### ISSUE TITLE
Impossible de télécharger

### ISSUE THREAD

**Issue by Sumonil** [thcolin/sensorr#155]
Salut, peu importe le film que j'essaye de télécharger j'ai cette erreur, avec n'importe quelle indexers:
![image](https://user-images.githubusercontent.com/34725275/82696863-33ee2b80-9c68-11ea-84f7-c18053bb6969.png)
Si tu as une idées, merci d'avance

**Comment by thcolin** [comment]
Hello,

Possible que tes indexers ne proposent que des lien magnet, vers quel lien t'amène l'icône 🎟️ d'une release ?

**Comment by Sumonil** [comment]
Salut, ca m'ouvre une nouvelle page avec cette erreur:
![image](https://user-images.githubusercontent.com/34725275/82725544-f88e4400-9cdd-11ea-8e99-4aefbdb89ae4.png)

**Comment by Sumonil** [comment]
et ca  c'est l'url: http://62.171.156.114:5070/proxy?url=aHR0cDovLzYyLjE3MS4xNTYuMTE0OjkxMTcvZGwvZ2t0b3JyZW50Lz9qYWNrZXR0X2FwaWtleT0zNmE1eWdjM2llaDRrY2J0eHQ3NXdtdGZmam8weGI4bSZwYXRoPVEyWkVTamhRTVdRNFVVVkpaRFJ3VDNRMlNuVnVSelEwTUV0SVIzUndNbU13YmtwWFdrUlNTVUY0VDI1ZlpGVjBkRkZhZUdoZlVFdFRTbUk0TWxFMmFrTnZVR2hUWDA1MWJVVkxUMGR1VFVneGFVMDVOSHBMY1dKUlJGQTNNSE5DV0hoME4yNVVaMGx1YTJOME5GcGZYMVpUWTI5VlVWZDFWRWRmWWtkQ2JIbHFSRkpZUkZOTVptOVNVRk5vVjNOTmJWUmtiVmQzT1dKeU1VOTNUemxxZVdKa1kxQjBXa3hqVGtWcU5uazBhSGxsVVZwZmJHMXFabUoxU2psMWNEWnVZVmRwY21JeU1tVk9RbUZIVUVzM04wZFVSakZIVm1ZeFUzQXcmZmlsZT1UaGUuTG92ZWJpcmRzLjIwMjAuRlJFTkNILldFQi1ETC1OT1RFQU0=

**Comment by thcolin** [comment]
Ok, en effet, ce sont bien des liens torrent [magnet](https://fr.wikipedia.org/wiki/Magnet_(standard)), Sensorr ne supporte pas ce format, il faut configurer tes Indexers afin que le fichier retourner pour le téléchargement d'une release soit un `.torrent`

**Comment by Sumonil** [comment]
Salut j'utilise Jackett je dois faire comment ?

**Comment by thcolin** [comment]
Utiliser des indexers qui renvoient bien des fichiers `.torrent`, tu peux le vérifier en utilisant manuellement Jackett
