### ISSUE TITLE
Login/mdp pas pris en compte

### ISSUE THREAD

**Issue by Majaxx** [thcolin/sensorr#183]
Bonjour, 
Je me suis rendu compte que meme en modifiant l'identifiant et le mot de passe cela ne fonctionner pas 
J'explique . 
La modification s'effectue bien dans le fichier de config , malheureusement une fois la page actualisé si je n'entre pas de mot de passe ou que je rentre n'importe quoi l'accès fonctionne quand même

**Comment by thcolin** [comment]
Fixed, thanks !
