### ISSUE TITLE
Jackett gives Magnet links wich is not compatible

### ISSUE THREAD

**Issue by MichelBaie** [thcolin/sensorr#206]
Hi,

When i click on any link to download the movie it says "Something went wrong during Fatman xxxx grabing : TypeError: Only absolute URLs are supported"

Do u have a fix ?

**Comment by thcolin** [comment]
Hi,

I think your XZNAB configuration might be wrong, you need to specify absolute URL, like `http://localhost:5060/torznab/aggregate/api`

**Comment by MichelBaie** [comment]
Je suis à l'aise avec l'Anglais, j'ai enquêté et certains trackers et même beaucoup d'ailleurs, renvoient des liens magnet.
Il faudrais rendre compatible de blackhole des magnet ou alors de les convertir ?

Par exemple 1337x ne renvoie que des magnets et pose problème :/

**Comment by MichelBaie** [comment]
Car ducoup je suis très limité en terme de trackers et c'est embêtant :/ J'utilise Jackett et un autre tracker fonctionne. Cela veut dire qu'il faut que je les testes 1 par 1 et les configure dans sensorr ?

**Comment by thcolin** [comment]
Yes, j'ai connaissance du problème des liens magnet avec la méthode de téléchargement "blackhole", j'ai commencé à étudier la solution de "convertir" les liens magnet en fichier `.torrent`, ça arrivera pour la prochaine version je pense, pas de date précise hélas

**Comment by MichelBaie** [comment]
:( Pas de problème, j'ai testé tout les indexers, en ai gardé une petite partie et sa marchera comme sa !

Mercii
