### ISSUE TITLE
Apple API HTTPS forcé ?

### ISSUE THREAD

**Issue by Aerya** [thcolin/sensorr#6]
Salut, j'ai installé un Jackett qui n'a pas de domaine lié et est en http://ip:port. Je remarque que Sensorr appelle quand même l'API en HTTPS. Est-il possible de ne pas forcer le SSL ?

**Comment by thcolin** [comment]
👋

Le HTTPS n'est pas forcé sur les XZNAB, si tu configure l'url en `http://192.168.0.42/api`, Sensorr l'appellera avec cet url précisément.

**Comment by laster13** [comment]
Je me permets d'intervenir dans ce post car je rencontre un soucis de fichier torrent à 0 octet des lors qu'il est téléchargé via une configuration en https://sensorr.domaine.com.
Je t'ai laissé un message sur mondedie
https://mondedie.fr/u/laster13
Merci

**Comment by thcolin** [comment]
J'aurais besoin de précisions :

* Tu pourrais me détailler ta configuration (Docker, URL des différents services - sensorr, xznab...)
* Est-ce que tu as des résultats des XZNAB ? Ou l'erreur n'est qu'au téléchargement ?
* Quel est l'origine de la recherche / téléchargement, web ou cron ?

**Comment by thcolin** [comment]
Fixé via #62
