### ISSUE TITLE
Impossible de sauvegarder la config

### ISSUE THREAD

**Issue by devIlluSioN** [thcolin/sensorr#7]
Bonjour
Je ne peux pas sauvegarder la configuration que je rentre sur http://127.0.0.1:5070/configure/configure 

J'ai une erreur 500 sur http://127.0.0.1:5070/api/configure. 

Ai-je loupé quelque chose ?

**Comment by thcolin** [comment]
Hello,

Tu utilise le conteneur Docker ? Si c'est le cas, fait attention au GUID et PUID utilisé !

**Comment by devIlluSioN** [comment]
Non j'ai fais un 
`npm run start`

**Comment by thcolin** [comment]
Tu peux vérifier les permissions du dossier `config` ?

**Comment by devIlluSioN** [comment]
drwxr-xr-x et avec un chmod 777 cela ne change rien.

**Comment by devIlluSioN** [comment]
<img width="384" alt="Capture d’écran 2019-06-13 à 10 10 34" src="https://user-images.githubusercontent.com/35778025/59415352-96d21400-8dc3-11e9-98a0-23cfd91a501e.png">

**Comment by thcolin** [comment]
Tu peux vérifier les logs de `pm2` ? (`pm2 logs`)

**Comment by devIlluSioN** [comment]
Dans mon terminal j'obtient cela à chaque clique sur le bouton save 

<img width="920" alt="Capture d’écran 2019-06-13 à 10 23 29" src="https://user-images.githubusercontent.com/35778025/59416294-668b7500-8dc5-11e9-8b17-137f12f5baeb.png">

**Comment by thcolin** [comment]
Tu peux me copier ta config (`config/config.json`) en la caviardant ? As tu essayé de l'éditer à la main ? Dans ton fichier `config/config.json` il doit manquer la clé `plex` : 

```
{
  [...],
  "plex": {
    "url": "",
    "pin": {
      "code": "",
      "id": ""
    },
    "token": ""
  }
}
```

**Comment by devIlluSioN** [comment]
Effectivement c'était bien ça le problème, il n'y avais pas la clé plex dans le fichier de config, je n'ai ajouté manuellement que la clé api de tmdb.
